version: '3.8'

services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://i12a202.p.ssafy.io:3306/m09
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
    expose:
      - "8080"
    networks:
      - mynetwork

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "3000"
    networks:
      - mynetwork

  embedded:
    build: ./embedded
    container_name: embedded
    expose:
      - "8765"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl/:/etc/nginx/ssl/
      - ./frontend/dist:/usr/share/nginx/html
      - /etc/letsencrypt/live/p.ssafy.io/fullchain.pem:/etc/nginx/ssl/fullchain.pem:ro
      - /etc/letsencrypt/live/p.ssafy.io/privkey.pem:/etc/nginx/ssl/privkey.pem:ro
    depends_on:
      - frontend
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
